#!/usr/bin/env bash
# sync-project.sh — Genera AGENTS.md e CLAUDE.md per un progetto ai4educ
# Uso: sync-project.sh [--check] [--all] [--project /path/to/project]
#   --project PATH   sync singolo progetto
#   --all            sync tutti i progetti elencati in projects.txt
#   --check          verifica se i file sono allineati (exit 1 se stale)
#   (default)        sync singolo progetto in $PWD

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
BLOCK_FILE="$REPO_ROOT/blocks/shared-rules.md"
VERSION="1.0"

# Colori
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    echo "Uso: sync-project.sh [--check] [--all] [--project PATH]"
    echo "  --project PATH   sync singolo progetto"
    echo "  --all            sync tutti i progetti elencati in projects.txt"
    echo "  --check          verifica se i file sono allineati (exit 1 se stale)"
    echo "  (default)        sync singolo progetto nella directory corrente"
    exit 1
}

# Legge il blocco canonico e calcola l'hash
read_block() {
    if [[ ! -f "$BLOCK_FILE" ]]; then
        echo -e "${RED}ERRORE: blocco canonico non trovato: $BLOCK_FILE${NC}" >&2
        exit 1
    fi
    BLOCK_HASH=$(sha256sum "$BLOCK_FILE" | cut -c1-12)
    BLOCK_CONTENT=$(cat "$BLOCK_FILE")
}

# Genera il contenuto del file progetto
generate() {
    local project_name="$1"
    cat <<EOF
<!-- ai4educ:shared-rules:start hash=$BLOCK_HASH -->
$BLOCK_CONTENT
<!-- ai4educ:shared-rules:end -->

## Project Context
Read \`CONTEXT.md\` for domain knowledge, architecture, conventions, and common tasks.

> GENERATED by ai4educ-shared-config/v$VERSION — DO NOT EDIT
> Source: blocks/shared-rules.md (hash: $BLOCK_HASH)
EOF
}

# Sincronizza un progetto
sync_project() {
    local project_dir="$1"
    local project_name
    project_name=$(basename "$project_dir")

    if [[ ! -d "$project_dir" ]]; then
        echo -e "${RED}ERRORE: directory non trovata: $project_dir${NC}" >&2
        return 1
    fi

    local generated
    generated=$(generate "$project_name")

    for target in AGENTS.md CLAUDE.md; do
        local target_path="$project_dir/$target"
        local current_hash="none"

        if [[ -f "$target_path" ]]; then
            current_hash=$(grep -oP 'hash=\K[a-f0-9]+' "$target_path" 2>/dev/null || echo "unknown")
        fi

        if [[ "$current_hash" == "$BLOCK_HASH" ]]; then
            echo -e "  ${GREEN}✓${NC} $target (già aggiornato)"
        else
            echo "$generated" > "$target_path"
            echo -e "  ${GREEN}✓${NC} $target (aggiornato: $current_hash → $BLOCK_HASH)"
        fi
    done

    # Controlla se esiste CONTEXT.md
    if [[ ! -f "$project_dir/CONTEXT.md" ]]; then
        echo -e "  ${YELLOW}⚠${NC} CONTEXT.md non trovato. Crealo con: cp templates/CONTEXT.md.template $project_dir/CONTEXT.md"
    fi
}

# Verifica allineamento senza scrivere
check_project() {
    local project_dir="$1"
    local project_name
    project_name=$(basename "$project_dir")
    local ok=true

    if [[ ! -d "$project_dir" ]]; then
        echo -e "${RED}ERRORE: directory non trovata: $project_dir${NC}" >&2
        return 1
    fi

    for target in AGENTS.md CLAUDE.md; do
        local target_path="$project_dir/$target"
        if [[ ! -f "$target_path" ]]; then
            echo -e "  ${RED}✗${NC} $target: mancante"
            ok=false
            continue
        fi
        local current_hash
        current_hash=$(grep -oP 'hash=\K[a-f0-9]+' "$target_path" 2>/dev/null || echo "unknown")
        if [[ "$current_hash" != "$BLOCK_HASH" ]]; then
            echo -e "  ${RED}✗${NC} $target: stale ($current_hash → $BLOCK_HASH)"
            ok=false
        else
            echo -e "  ${GREEN}✓${NC} $target"
        fi
    done

    if [[ ! -f "$project_dir/CONTEXT.md" ]]; then
        echo -e "  ${YELLOW}⚠${NC} CONTEXT.md mancante"
    fi

    $ok
}

# --- Main ---

read_block

MODE=""
PROJECT_DIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) MODE="check"; shift ;;
        --all) MODE="all"; shift ;;
        --project) PROJECT_DIR="$2"; shift 2 ;;
        --help|-h) usage ;;
        *) echo "Opzione sconosciuta: $1"; usage ;;
    esac
done

if [[ "$MODE" == "all" ]]; then
    PROJECTS_FILE="$REPO_ROOT/projects.txt"
    if [[ ! -f "$PROJECTS_FILE" ]]; then
        echo -e "${RED}ERRORE: projects.txt non trovato in $REPO_ROOT${NC}" >&2
        echo "Crea un file con un path di progetto per riga."
        exit 1
    fi
    echo "Sincronizzazione di tutti i progetti..."
    while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^# ]] && continue
        echo -e "\n${line}:"
        sync_project "$line"
    done < "$PROJECTS_FILE"
    echo -e "\n${GREEN}Fatto.${NC}"

elif [[ "$MODE" == "check" ]]; then
    if [[ -n "$PROJECT_DIR" ]]; then
        check_project "$PROJECT_DIR"
    else
        check_project "$PWD"
    fi

else
    if [[ -n "$PROJECT_DIR" ]]; then
        sync_project "$PROJECT_DIR"
    else
        sync_project "$PWD"
    fi
fi
