#!/usr/bin/env bash
# sync-global.sh — Genera i file globali per tutti i coding agent
# Uso: sync-global.sh [--check]
#   (default)  genera ~/.pi/agent/AGENTS.md, ~/.claude/CLAUDE.md, ~/.codex/AGENTS.md,
#              ~/.opencode/AGENTS.md
#   --check    verifica se i file globali sono allineati (exit 1 se stale)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
GUIDELINES_FILE="$REPO_ROOT/blocks/global-guidelines.md"
SHARED_CONFIG_DIR="$REPO_ROOT"
VERSION="1.0"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

usage() {
    echo "Uso: sync-global.sh [--check]"
    echo "  (default)  genera i file globali"
    echo "  --check    verifica allineamento (exit 1 se stale)"
    exit 1
}

read_guidelines() {
    if [[ ! -f "$GUIDELINES_FILE" ]]; then
        echo -e "${RED}ERRORE: global-guidelines.md non trovato: $GUIDELINES_FILE${NC}" >&2
        exit 1
    fi
    GUIDELINES_HASH=$(sha256sum "$GUIDELINES_FILE" | cut -c1-12)
    GUIDELINES_CONTENT=$(cat "$GUIDELINES_FILE")
}

generate() {
    cat <<EOF
$GUIDELINES_CONTENT

---

## Sync delle istruzioni

I blocchi canonici delle istruzioni vivono in \`$SHARED_CONFIG_DIR\`.
Quando modifichi \`blocks/shared-rules.md\` o \`blocks/global-guidelines.md\`:
1. \`git pull\` in \`$SHARED_CONFIG_DIR\`
2. \`./scripts/sync-global.sh\`        — aggiorna i file globali (~/.pi, ~/.claude, ~/.codex, ~/.opencode)
3. \`./scripts/sync-project.sh --all\`  — propaga le regole di processo a tutti i progetti

I file \`AGENTS.md\` e \`CLAUDE.md\` nei progetti sono generati — **NON modificarli a mano**.
\`CONTEXT.md\` invece è manuale e specifico per ogni progetto.

> GENERATED by ai4educ-shared-config/v$VERSION — DO NOT EDIT
> Source: blocks/global-guidelines.md (hash: $GUIDELINES_HASH)
EOF
}

sync_all() {
    local GUIDELINES_HASH
    read_guidelines
    local generated
    generated=$(generate)

    # Mappa tool → path globale
    declare -A TARGETS=(
        ["$HOME/.pi/agent/AGENTS.md"]="Pi"
        ["$HOME/.claude/CLAUDE.md"]="Claude Code"
        ["$HOME/.codex/AGENTS.md"]="Codex"
        ["$HOME/.opencode/AGENTS.md"]="OpenCode"
    )

    for target_path in "${!TARGETS[@]}"; do
        local tool_name="${TARGETS[$target_path]}"
        local target_dir
        target_dir=$(dirname "$target_path")

        if [[ ! -d "$target_dir" ]]; then
            echo -e "  ${RED}✗${NC} $tool_name: directory non trovata ($target_dir) — skip"
            continue
        fi

        local current_hash="none"
        if [[ -f "$target_path" ]]; then
            current_hash=$(grep -oP 'Source: blocks/global-guidelines.md \(hash: \K[a-f0-9]+' "$target_path" 2>/dev/null || echo "unknown")
        fi

        if [[ "$current_hash" == "$GUIDELINES_HASH" ]]; then
            echo -e "  ${GREEN}✓${NC} $tool_name: $target_path (già aggiornato)"
        else
            echo "$generated" > "$target_path"
            echo -e "  ${GREEN}✓${NC} $tool_name: $target_path ($current_hash → $GUIDELINES_HASH)"
        fi
    done
}

check_all() {
    read_guidelines
    local ok=true

    declare -A TARGETS=(
        ["$HOME/.pi/agent/AGENTS.md"]="Pi"
        ["$HOME/.claude/CLAUDE.md"]="Claude Code"
        ["$HOME/.codex/AGENTS.md"]="Codex"
        ["$HOME/.opencode/AGENTS.md"]="OpenCode"
    )

    for target_path in "${!TARGETS[@]}"; do
        local tool_name="${TARGETS[$target_path]}"

        if [[ ! -f "$target_path" ]]; then
            echo -e "  ${RED}✗${NC} $tool_name: mancante ($target_path)"
            ok=false
            continue
        fi

        local current_hash
        current_hash=$(grep -oP 'Source: blocks/global-guidelines.md \(hash: \K[a-f0-9]+' "$target_path" 2>/dev/null || echo "unknown")
        if [[ "$current_hash" != "$GUIDELINES_HASH" ]]; then
            echo -e "  ${RED}✗${NC} $tool_name: stale ($current_hash → $GUIDELINES_HASH)"
            ok=false
        else
            echo -e "  ${GREEN}✓${NC} $tool_name"
        fi
    done

    $ok
}

# --- Main ---

MODE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check) MODE="check"; shift ;;
        --help|-h) usage ;;
        *) echo "Opzione sconosciuta: $1"; usage ;;
    esac
done

if [[ "$MODE" == "check" ]]; then
    check_all
else
    echo "Sincronizzazione file globali..."
    sync_all
    echo -e "\n${GREEN}Fatto.${NC}"
fi
